year = (input("Enter your year: "))
genre = (input("Enter your genre: "))
album = (input("Enter your album: "))
title = (input("Enter your song title: "))
artist = (input("Enter your artist: "))

print("----------------------------")
print("SONG DETAILS")
print("----------------------------")

print(f"Year Released: {year}")
print(f"Genre: {genre}")
print(f"Album: {album}")
print(f"Title: \"{title}\"")
print(f"Artist: {artist}")